export const Loading = () => {
	return (
		<div className="overlay bg-black top-0 bottom-0 start-0 end-0 d-block position-absolute z-3 opacity-75 d-flex justify-content-center align-items-center text-center flex-column position-fixed">
			<svg
				xmlns="http://www.w3.org/2000/svg"
				width="140"
				height="140"
				viewBox="-20 -20 104 104"
				fill="none"
			>
				<defs>
					<filter
						id="glow"
						x="-100%"
						y="-100%"
						width="300%"
						height="300%"
					>
						{/* 強化發光效果，使用更高的 stdDeviation 和更亮的透明度 */}
						<feDropShadow
							dx="0"
							dy="0"
							stdDeviation="2"
							floodColor="white"
							floodOpacity="0.8"
						/>
						<feDropShadow
							dx="0"
							dy="0"
							stdDeviation="6"
							floodColor="white"
							floodOpacity="0.6"
						/>
						<feDropShadow
							dx="0"
							dy="0"
							stdDeviation="10"
							floodColor="white"
							floodOpacity="0.4"
						/>
					</filter>
				</defs>
				<path
					d="M2 12h2.49a2 2 0 0 0 1.93-1.46l2.35-8.36a.25.25 0 0 1 .48 0l2.35 19.64a.25.25 0 0 0 .48 0l2.35-8.36A2 2 0 0 1 19.52 12H22"
					stroke="white"
					strokeWidth="2"
					strokeLinecap="round"
					strokeLinejoin="round"
					pathLength="1"
					strokeDasharray="1"
					strokeDashoffset="1"
					filter="url(#glow)"
				>
					<animate
						attributeName="stroke-dashoffset"
						from="1"
						to="0"
						dur="1s"
						repeatCount="indefinite"
					/>
					<animate
						attributeName="stroke-opacity"
						values="0.3;0.9;0.3"
						dur="1s"
						repeatCount="indefinite"
					/>
				</path>
			</svg>
		</div>
	);
};
